### ISSUE TITLE
转换过去的代码运行问题

### ISSUE THREAD

**Issue by ericfjl** [linsneider/DiyCodeAndroid#1]
调试的时候执行到以下代码行停住了

// X5内核初始化接口
QbSdk.initX5Environment(application, null);

**Comment by linsneider** [comment]
我试了一下，这行代码会停留久一点，你等一下就好了。

**Comment by linsneider** [comment]
@ericfjl 我试了一下，这行代码会停留久一点，你等一下就好了。
